In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as nu
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
%matplotlib inline

In [2]:
iris=load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
y = iris.target[:100]

In [5]:
x = iris.data[:100]

In [24]:
x = scale(x) #NORMALIZE X
x[:5]

array([[-0.5810659 ,  0.85713543, -1.01435952, -1.03824799],
       [-0.89430898, -0.19845007, -1.01435952, -1.03824799],
       [-1.20755205,  0.22378413, -1.08374115, -1.03824799],
       [-1.36417359,  0.01266703, -0.94497788, -1.03824799],
       [-0.73768744,  1.06825253, -1.01435952, -1.03824799]])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 101)
x_train.shape

(80, 4)

In [8]:
x_1 = nu.ndarray((80))
x_2 = nu.ndarray((80))
x_3 = nu.ndarray((80))
x_4 = nu.ndarray((80))
for i in range(80):
    x_1[i] = x_train[i][0]
    x_2[i] = x_train[i][1]
    x_3[i] = x_train[i][2]
    x_4[i] = x_train[i][3]

In [9]:
theta_0 = nu.exp(-6)
theta_1 = nu.exp(-6)
theta_2 = nu.exp(-6)
theta_3 = nu.exp(-6)
theta_4 = nu.exp(-6)

### y_pred = theta_0 + theta_1 * x1 + theta_2 * x2 + theta_3 * x3 + theta_4 * x4

In [10]:
alpha = 0.00005
reg_p = 1
m=y_train.size

In [11]:
def get_update(x1, x2, x3, x4, y, wt_0, wt_1, wt_2, wt_3, wt_4, m, a, reg_p):
    update_0 = wt_0
    update_1 = wt_1
    update_2 = wt_2
    update_3 = wt_3
    update_4 = wt_4
    #print( round((1 / m),10))
    for i in range(m-1):
        update_0 -=  ((a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1)) + (alpha * reg_p * (1/m)))
        update_1 -=  ((a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x1[i]) + (alpha * reg_p * (1/m)))
        update_2 -=  ((a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x2[i]) + (alpha * reg_p * (1/m)))
        update_3 -=  ((a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x3[i]) + (alpha * reg_p * (1/m)))
        update_4 -=  ((a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x4[i]) + (alpha * reg_p * (1/m)))
        
    return update_0, update_1, update_2, update_3, update_4

In [12]:
for i in range(10000):
    update_0, update_1, update_2, update_3, update_4 = get_update(x_1, x_2, x_3, x_4, y, theta_0, theta_1, theta_2,  theta_3, theta_4, m, alpha, reg_p)
    theta_0 = theta_0 - update_0
    theta_1 = theta_1 - update_1
    theta_2 = theta_2 - update_2
    theta_3 = theta_3 - update_3
    theta_4 = theta_4 - update_4
print(theta_0, theta_1, theta_2, theta_3, theta_4)

4.28131052747e-05 4.70716343975e-05 4.67186027119e-05 4.85311816931e-05 4.8092415884e-05


In [13]:
theta = nu.array([theta_1, theta_2, theta_3, theta_4])

In [14]:
g_x = nu.matmul(x_test,theta)
g_x

array([ -1.11942468e-05,  -1.50527816e-04,  -5.29641199e-05,
         4.54313248e-05,   2.58267439e-05,  -4.63033884e-05,
         1.26987668e-04,   1.95126885e-04,  -1.24657367e-04,
        -2.43891027e-04,   5.57676986e-05,  -1.36421038e-04,
        -1.49364888e-04,   8.17510616e-05,  -1.45832907e-04,
        -5.37753810e-05,   2.37560461e-04,  -2.50846520e-05,
        -1.59414842e-04,  -4.86292443e-05])

In [15]:
y_pred = 1/(1+nu.exp((g_x+theta_0)*-1))

In [16]:
y_pred

array([ 0.5000079 ,  0.49997307,  0.49999746,  0.50002206,  0.50001716,
        0.49999913,  0.50004245,  0.50005948,  0.49997954,  0.49994973,
        0.50002465,  0.4999766 ,  0.49997336,  0.50003114,  0.49997425,
        0.49999726,  0.50007009,  0.50000443,  0.49997085,  0.49999855])

In [17]:
def bin(y,size):
    for i in range(size):
        if y[i]<0.5:
            y[i]=0
        else:
            y[i]=1
    return y    

In [18]:
bin(y_pred,y_pred.size),y_test

(array([ 1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
         1.,  0.,  0.,  1.,  1.,  0.,  0.]),
 array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0]))

# TEST ACCURACY

In [19]:
accuracy_score(y_pred,y_test)

0.90000000000000002

In [20]:
y_on = nu.matmul(x_train,theta) + theta_0
y_o = (1/(1+nu.exp(y_on*-1)))

# TRAIN ACCURACY

In [21]:
accuracy_score(bin(y_o,y_o.size),y_train)

0.86250000000000004