In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as nu
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
%matplotlib inline

In [2]:
iris=load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
y = iris.target[:100]

In [5]:
x = iris.data[:100]

In [6]:
x = scale(x) # Normalizing dataset
x[:5]

array([[-0.5810659 ,  0.85713543, -1.01435952, -1.03824799],
       [-0.89430898, -0.19845007, -1.01435952, -1.03824799],
       [-1.20755205,  0.22378413, -1.08374115, -1.03824799],
       [-1.36417359,  0.01266703, -0.94497788, -1.03824799],
       [-0.73768744,  1.06825253, -1.01435952, -1.03824799]])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=100)
x_train.shape

(80, 4)

In [8]:
x_1 = nu.ndarray((80))
x_2 = nu.ndarray((80))
x_3 = nu.ndarray((80))
x_4 = nu.ndarray((80))
for i in range(80):
    x_1[i] = x_train[i][0]
    x_2[i] = x_train[i][1]
    x_3[i] = x_train[i][2]
    x_4[i] = x_train[i][3]

In [9]:
theta_0 = 0.0001
theta_1 = 0.0001
theta_2 = 0.0001
theta_3 = 0.0001
theta_4 = 0.0001

### y_pred = theta_0 + theta_1 * x1 + theta_2 * x2 + theta_3 * x3 + theta_4 * x4

In [10]:
alpha = 0.0005
m=y_train.size

In [11]:
def get_update(x1, x2, x3, x4, y, wt_0, wt_1, wt_2, wt_3, wt_4, m, a):
    update_0 = wt_0
    update_1 = wt_1
    update_2 = wt_2
    update_3 = wt_3
    update_4 = wt_4
    #print( round((1 / m),10))
    for i in range(m-1):
        update_0 +=  a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1)
        update_2 +=  a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x2[i]
        update_3 +=  a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x3[i]
        update_4 +=  a * (1/m) * (1/(1+nu.exp(((wt_4 * x4[i]) + (wt_3 * x3[i]) + (wt_2 * x2[i]) + (wt_1 * x1[i]) + wt_0))) - y[i]) * (-1) * x4[i]
        
    return update_0, update_1, update_2, update_3, update_4

In [12]:
for i in range(10000):
    update_0, update_1, update_2, update_3, update_4 = get_update(x_1, x_2, x_3, x_4, y, theta_0, theta_1, theta_2,  theta_3, theta_4, m, alpha)
    theta_0 = theta_0 - update_0
    theta_1 = theta_1 - update_1
    theta_2 = theta_2 - update_2
    theta_3 = theta_3 - update_3
    theta_4 = theta_4 - update_4
print(theta_0, theta_1, theta_2, theta_3, theta_4)

6.56165664228e-05 0.0 -1.76317977579e-05 4.85491891451e-05 5.22038086791e-05


In [13]:
theta = nu.array([theta_1, theta_2, theta_3, theta_4])

In [14]:
g_x = nu.matmul(x_test,theta)
g_x

array([ -1.09566795e-04,   9.15305097e-05,  -8.95703665e-05,
        -6.79945614e-05,  -1.14129392e-04,  -9.32109557e-05,
        -1.21928092e-04,  -1.44616288e-04,   1.60291038e-04,
        -1.04105911e-04,   1.19294388e-04,   1.14945895e-04,
         9.51710990e-05,   8.62600082e-05,   1.00005864e-04,
         1.28641216e-04,   1.57004400e-04,  -1.04813814e-04,
        -1.12663050e-04,  -1.08100452e-04])

In [15]:
y_pred = 1/(1+nu.exp((g_x+theta_0)*-1))

In [16]:
y_pred

array([ 0.49998901,  0.50003929,  0.49999401,  0.49999941,  0.49998787,
        0.4999931 ,  0.49998592,  0.49998025,  0.50005648,  0.49999038,
        0.50004623,  0.50004514,  0.5000402 ,  0.50003797,  0.50004141,
        0.50004856,  0.50005566,  0.4999902 ,  0.49998824,  0.49998938])

In [17]:
def bin(y,size):
    for i in range(size):
        if y[i]<0.5:
            y[i]=0
        else:
            y[i]=1
    return y    

In [18]:
bin(y_pred,y_pred.size),y_test

(array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  0.,  0.,  0.]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]))

# TEST ACCURACY

In [19]:
accuracy_score(y_pred,y_test)

1.0

In [20]:
y_on = nu.matmul(x_train,theta) + theta_0
y_o = (1/(1+nu.exp(y_on*-1)))

# TRAIN ACCURACY

In [21]:
accuracy_score(bin(y_o,y_o.size),y_train)

1.0